/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum department { 
  Sale, Marketing, IT, Management, Accounting  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"department\",\"namespace\":\"com.example\",\"symbols\":[\"Sale\",\"Marketing\",\"IT\",\"Management\",\"Accounting\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
